rm_netxduo_ether receive path fixes regarding netx interface index and pointer
renesas/fsp pull request #374
Opened 2024-09-30 12:12 UTC by elrafoon

Without this fixes, rm_netxduo_ether is only usable if it is the primary interface of given netxduo NX_IP stack.

But that's not always the case!

2024-10-07 21:50 UTC, jritchey-renesas requested changes
I agree, this is a bug in the existing driver.

Could you also apply this change to lines 788, and 833? The correct interface index needs to be provided to `_nx_ip_driver_link_status_event`.
```c
            /* Notify NetX that the link is up. */
            p_netxduo_ether_instance->p_ctrl->p_interface->nx_interface_link_up = NX_TRUE;
            _nx_ip_driver_link_status_event(p_netxduo_ether_instance->p_ctrl->p_ip,
                                            p_netxduo_ether_instance->p_ctrl->p_interface->nx_interface_index);
```
```c
            /* Notify NetX that the link is down. */
            p_netxduo_ether_instance->p_ctrl->p_interface->nx_interface_link_up = NX_FALSE;
            _nx_ip_driver_link_status_event(p_netxduo_ether_instance->p_ctrl->p_ip,
                                            p_netxduo_ether_instance->p_ctrl->p_interface->nx_interface_index);
```

2024-10-08 13:03 UTC, jritchey-renesas commented on ra/fsp/src/rm_netxduo_ether/rm_netxduo_ether.c
> +                driver_req_ptr->nx_ip_driver_ptr->nx_ip_interface[interface_ptr->nx_interface_index].nx_interface_link_up;
```suggestion
                *(driver_req_ptr->nx_ip_driver_return_ptr) = interface_ptr->nx_interface_link_up;
```

2024-10-08 20:25 UTC, renesas-abigail commented
This PR is tracked internally by FSPRA-3840.

2024-10-25 17:21 UTC, closed without merging

2024-10-29 08:10 UTC, elrafoon commented
Sorry for the delay, I was busy on a project.

Shall I do something, or is it resolved?

2024-10-29 13:34 UTC, jritchey-renesas commented
Its no worries, the fix was added in the v5.6.0 release. Thanks for bringing the issue to our attention!